### ISSUE TITLE
errore con libri contenenti pulsanti di "traduzione"

### ISSUE THREAD

**Issue by Made3D-Italia** [Leone25/bSmart-downloader#13]
Ciao, con libri dove ci sono paggine con contenuti multimediali (tipo bottoni di lingua) succede che lo scaricamento si interrompe e si ottiene questo errore
{
filename: 'DEA17C_15052_1AP_036.pdf',
md5: '75fc1cb5717cfd2484f8b1f465dbab32',
orig_size: 230398,
start: 11808,
path: 'pagine'
}
C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28
_this.catalog.Pages().traverse(function (node, ref) {
^

TypeError: _this.catalog.Pages is not a function
at PDFDocument.computePages [as populate] (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
at Cache.access (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
at PDFDocument.getPages (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
at PDFDocument. (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
at step (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
at Object.next (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
at fulfilled (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:112:62)

Node.js v18.15.0

**Comment by Made3D-Italia** [comment]
in realtà i pulsanti che portano alle traduzioni non fanno altro che linkare ad altre pagine del libro poste in fondo... e sembrano creare l'errore di cui sopra

**Comment by edobett** [comment]
Same problem with my books

**Comment by Leone25** [comment]
Perfavore guardate qua https://github.com/Leone25/bSmart-downloader/issues/16#issuecomment-1624854796
