### ISSUE TITLE
Download fallito

### ISSUE THREAD

**Issue by SalvatoreYTP** [Leone25/bSmart-downloader#17]
Please input book id: 141934
Downloading pages
Progress 0.00%
Progress 0.00%
Progress 3.83%
...
Progress 41.39%
Error Downloading page {
  e: Error: invalid initialation vector size (must be 16 bytes)
      at new ModeOfOperationCBC (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\aes-js\index.js:439:19)
      at C:\Users\salva\Desktop\bSmart-downloader-main\index.js:22:26
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  file: <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 55 54 46 2d 38 22 3f 3e 0a 3c 45 72 72 6f 72 3e 3c 43 6f 64 ... 193 more bytes>
} 173 0 https://s3-eu-west-1.amazonaws.com/atlas.bsmart.it/d/4/d41d8cd98f00b204e9800998ecf8427e
C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\validators.js:140
    throw new TypeError(exports.createTypeErrorMsg(value, valueName, types));
          ^

TypeError: `pdf` must be of type `string` or `Uint8Array` or `ArrayBuffer`, but was actually of type `undefined`
    at Object.exports.assertIs (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at Function.<anonymous> (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:122:33)
    at step (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\tslib\tslib.js:111:16)
    at Function.PDFDocument.load (C:\Users\salva\Desktop\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:116:24)
    at C:\Users\salva\Desktop\bSmart-downloader-main\index.js:106:44
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Leone25** [comment]
sembra che lo script stia provando a scaricare una pagina che non esiste, non saprei perchè...
