### ISSUE TITLE
Errore durante il download di due libri

### ISSUE THREAD

**Issue by DJLeleX** [Leone25/bSmart-downloader#18]
Please input book id:99763
Downloading pages
....
Progress 6.05%
C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28
            _this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

------------------------------------------------------------------------------------------------------------------------------------------------
Please input book id:101081
Downloading pages
....
Progress 66.87%
C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28
            _this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\DJLeleX\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

Non so se eri a conoscenza di questo problema. Questi due libri non vengono scaricati neanche con altri downloader (ad esempio https://github.com/FelixFrog/pdfgrabber)

**Comment by DJLeleX** [comment]
Ok ho visto i tuoi link al issue #16 dove suggerisci una soluzione... Penso che potrebbe essere utile che tu la iinserisca anche nella descrizione dello script.
Grazie e buona giornata!

**Comment by Leone25** [comment]
in che modo non ti funziona il metodo alternativo?

**Comment by DJLeleX** [comment]
"commentando linea 109, 110, 111, 118 (essenzialmente devi aggiungere // all'inizio di ogni riga), e scommentare linea 107 (rimuovere gli //) e poi eseguire nuovamente lo script."

Se faccio questi commenti, lo script non funziona più...

**Comment by Leone25** [comment]
hai creato la cartella temp nella stessa cartella dello script?

**Comment by DJLeleX** [comment]
Certo!
Il fatto è che lo script non ha senso se commento quelle linee di codice.. anche perché ad esempio la riga 107 non è commentata..
Penso che il numero di righe da commentare/rimuovere il commento sia cambiato da quando hai modificato il codice..

**Comment by Leone25** [comment]
hmmm si probabilmente ho cambiato il codice nel frattempo

quando hai eseguito il comando che ti da il merge.js hai cambiato la cartella con `cd temp`?

**Comment by Leone25** [comment]
Ho deciso di fare un aggiornamento, se scarichi di nuovo tutto puoi eseguire `node index.js --pdftk` e dovrebbe fare tutto da solo

**Comment by DJLeleX** [comment]
Ti confermo che avevo eseguito tutto correttamente, anche spostarmi nella cartella temp prima di eseguire il comando merge.js.

Comunque grazie mille per il supporto e per l'aggiornamento, ora funziona alla perfezione!
