### ISSUE TITLE
Download fallito

### ISSUE THREAD

**Issue by GioCa65** [Leone25/bSmart-downloader#22]
Progress 66.86%
Error Downloading page {
  e: Error: invalid initialation vector size (must be 16 bytes)
      at new ModeOfOperationCBC (C:\Users\*****\Downloads\bSmart\node_modules\aes-js\index.js:439:19)
      at C:\Users\*****\Downloads\bSmart\index.js:65:26
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  file: <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 55 54 46 2d 38 22 3f 3e 0a 3c 45 72 72 6f 72 3e 3c 43 6f 64 ... 193 more bytes>
} 341 0 https://s3-eu-west-1.amazonaws.com/atlas.bsmart.it/d/4/d41d8cd98f00b204e9800998ecf8427e
C:\Users\*****\Downloads\bSmart\node_modules\pdf-lib\cjs\utils\validators.js:140
    throw new TypeError(exports.createTypeErrorMsg(value, valueName, types));
          ^

TypeError: `pdf` must be of type `string` or `Uint8Array` or `ArrayBuffer`, but was actually of type `undefined`
    at exports.assertIs (C:\Users\*****\Downloads\bSmart\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at Function.<anonymous> (C:\Users\*****\Downloads\bSmart\node_modules\pdf-lib\cjs\api\PDFDocument.js:122:33)
    at step (C:\Users\*****\Downloads\bSmart\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\*****\Downloads\bSmart\node_modules\tslib\tslib.js:122:57)
    at C:\Users\*****\Downloads\bSmart\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\*****\Downloads\bSmart\node_modules\tslib\tslib.js:111:16)
    at PDFDocument.load (C:\Users\*****\Downloads\bSmart\node_modules\pdf-lib\cjs\api\PDFDocument.js:116:24)
    at C:\Users\*****\Downloads\bSmart\index.js:184:48
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Leone25** [comment]
Interessante, non sei il promo ad avere questo problema... magari è cambiato qualcosa, devo esplorare...

**Comment by Leone25** [comment]
Hmmmm, decodificando l'hex sembrerebbe che ci sia un file che non si riesce ad aprire, il server da errore e poi lo script tenta di decryptarlo crashando...

mi potresti contattare in privato su twitter (stesso nome + 03)?
