### ISSUE TITLE
Errore nel download di alcuni libri

### ISSUE THREAD

**Issue by NioBee** [Leone25/bSmart-downloader#5]
Buongiorno, su alcuni libri oggi quando tento il download ricevo un msg di errore:
`Downloading pages
Progress 0.00%
Progress 0.00%
Progress 2.96%
Error Downloading page {
  e: Error: invalid ciphertext size (must be multiple of 16 bytes)
      at ModeOfOperationCBC.decrypt (C:\bSmart-downloader-main\node_modules\aes-js\index.js:475:19)
      at C:\bSmart-downloader-main\index.js:29:45
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  file: <Buffer 3c 3f 78 6d 6c 6f 72 72 45 2f 3c 3e 64 49 74 73 6f 48 2f 3c 3d 63 44 6a 45 69 79 4e 36 34 56 45 41 67 6f 77 7a 49 67 30 72 32 6d 78 41 71 54 71 34 43 ... 257 more bytes>
} 41 0 https://s3-eu-west-1.amazonaws.com/cetem.bsmart.it/8/6/86c05b0766b9997674c562a69f5a94bd
C:\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\validators.js:140
    throw new TypeError(exports.createTypeErrorMsg(value, valueName, types));
          ^

TypeError: `pdf` must be of type `string` or `Uint8Array` or `ArrayBuffer`, but was actually of type `undefined`
    at Object.exports.assertIs (C:\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at Function.<anonymous> (C:\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:122:33)
    at step (C:\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at C:\bSmart-downloader-main\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\bSmart-downloader-main\node_modules\tslib\tslib.js:111:16)
    at Function.PDFDocument.load (C:\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:116:24)
    at C:\bSmart-downloader-main\index.js:172:44
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\bSmart-downloader-main>`

Temo che il problema non sia legato specificatamente alla repo, ma dipenda proprio dalla piattaforma MyBsmart, perchè anche consultando i libri da web trovo qualche pagina bianca ogni tanto.. tuttavia ho pensato comunque di segnalarlo nel caso ci fosse già una soluzione nota.. Premetto che su PC tramite app MyBsmart ho già fatto il download del libro tempo addietro (che ora l'app mi chiede di aggiornare - ma che non ho aggiornato), si può in qualche modo usare questa copia in locale per salvarsi il pdf?

**Comment by Leone25** [comment]
Grazie per la segnalazione
Leggendo ciò che dice devo darle ragione che probabilmente è un problema di bsmart quindi forse è meglio contattare loro e segnalargli il problema (ovviamente senza menzionare questo script)
Per quanto riguarda l'usare la versione scaricata, devo ammettere che non ho mai esplorato a fondo come funzioni l'app desktop di bsmart, quindi non le so dire. Credo che i file vengano salvati nella cartella appdata, magari se cerca da quelle parti e trova un file col nome del file che le da errore può integrarlo manualmente, ma questo è un processo lungo e laborioso che sconsiglio per i non esperti
Spero di averla aiutata
