### ISSUE TITLE
errore libri bSmart

### ISSUE THREAD

**Issue by StarNumber12046** [Leone25/bSmart-downloader#9]
```
            _this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\franc\reBooks\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\franc\reBooks\bSmart-downloader\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\franc\reBooks\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\franc\reBooks\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\franc\reBooks\bSmart-downloader\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\franc\reBooks\bSmart-downloader\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\franc\reBooks\bSmart-downloader\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.10.0
```

**Comment by Leone25** [comment]
Ho paura che sia un errore dovuto ad un bug in pdf lib anche perché non menziona un singolo file dello script, non saprei come aiutarti

**Comment by DanieleEsposito** [comment]
Non c'è nessuna possibilità di aggirarlo? Ho lo stesso problema

**Comment by Leone25** [comment]
ripeto, senza più contesto è difficile capire che cosa non funziona

**Comment by DanieleEsposito** [comment]
Che tipo di contesto ti può servire?

**Comment by DanieleEsposito** [comment]
Please input book id:4
Downloading pages
Progress 0.00%
Progress 0.00%
Progress 22.81%
Progress 22.81%
{
  filename: 'LOE17C_32653_P_C01.pdf',
  md5: '5f0681389bbf6f1f1c64cb0dda815812',
  orig_size: 280190,
  start: 14288,
  path: 'pagine'
}
C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28
            _this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\espos\Downloads\bSmart-downloader-main\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2

**Comment by Leone25** [comment]
beh ... è già interessante che non lo fa subito, potresti per favore creare una cartella chiamata `temp` nella cartella dove c'è lo script, e poi modificare lo script, commentando linea 109, 110, 111, 118 (essenzialmente devi aggiungere `//` all'inizio di ogni riga), e scommentare linea 107 (rimuovere gli `//`) e poi eseguire nuovamente lo script e poi nella cartella `temp` guardare che i pdf siano tutti a posto?

**Comment by DanieleEsposito** [comment]
Sì confermo, ha scaricato 148 file pdf!

**Comment by Leone25** [comment]
controllali, soprattutto i primi, guarda se si aprono senza problemi

**Comment by DanieleEsposito** [comment]
Sì, si aprono!

**Comment by Leone25** [comment]
per caso è un libro in particolare che non va? o sono tutti? magari ce l'ho anch'io

**Comment by DanieleEsposito** [comment]
È di inglese, si chiama Treasure

**Comment by Leone25** [comment]
come non detto, comunque ho guardato e adesso l'ha iniziato a fare anche a me con un libro che prima mi funzionava

ho trovato la pagina specifica che da errore, adesso creo una issue sulla pagina della libreria, ma dubito che riescano a fixarlo in tempo utile

ho anche provato altre versioni più vecchie e da lo stesso errore, quindi non si può bypassare così.

ciò che ti posso proporre, dato che il download nella cartella temp funziona, è di installare `pdftk` che è un programma a linea di comando che ti permetterà con l'aiuto dell script `merge.js` di creare un pdf unico.

Per utilizzarlo, installa `pdftk` da qui https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/ , la versione gratuita è sufficiente. Una volta installato (supponendo che le modifiche che ti ho proposto nei messaggi precedenti sono ancora presenti), fai come per scaricare un libro normalmente (se non hai eliminato file o tentato di scaricare altri libri puoi saltare questo passaggio, ricordati che quando vuoi scaricare un nuovo libro devi prima svuotare la cartella temp), una volta che lo script ha terminato, esegui il comando `node merge.js`, ti dovrebbe restituire un comando piuttosto lungo che inizia con `pdftk` e termina con `cat pog.pdf`, selezionalo tutto e copialo, adesso cambia la cartella scrivendo nel terminale (lo stesso dove hai fatto girare lo script) `cd temp`, e poi incolla ed esegui il comando che hai copiato prima, dovrebbe comparire nella cartella il pdf completo sotto forma di `pog.pdf`.

**Comment by DanieleEsposito** [comment]
Grazie mille, sei gentilissimo. Appena posso provo!

**Comment by Made3D-Italia** [comment]
Ciao, con libri dove ci sono paggine con contenuti multimediali (tipo bottoni di lingua) succede che lo scaricamento si interrompe e si ottiene questo errore
{
  filename: 'DEA17C_15052_1AP_036.pdf',
  md5: '75fc1cb5717cfd2484f8b1f465dbab32',
  orig_size: 230398,
  start: 11808,
  path: 'pagine'
}
C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28
            _this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\Valerio\Downloads\bSmart-downloader-main\bSmart-downloader-main\node_modules\tslib\tslib.js:112:62)

Node.js v18.15.0

**Comment by Leone25** [comment]
ah quindi è quello che fa crashare pdf-lib ...

come ho detto prima però fino a quando non fixano la libreria non c'è modo di risolvere quindi se vuoi puoi seguire le istruzioni che ho scritto precedentemente per scaricare le pagine separatamente e poi unirle manualmente
